import {
  Organization,
  Project,
  SponsorshipIntent,
  User,
  VolunteerApplication,
  AuditLogEntry,
  VolunteerBadge,
  CorporateTeamBooking,
  ProBonoDeliverable,
  ArcoRequest,
  CryptographicAuditBlock,
  ImpactTokenWallet,
  ImpactTokenTransaction,
  SoulboundImpactBadge,
  ImpactPerkReward,
  LegalAdhesionTerm,
} from '../types';

export const VOLUNTEER_BADGES: VolunteerBadge[] = [
  {
    id: 'badge_first_step',
    title: 'Primer Paso Solidario',
    description: 'Completó su primera postulación de voluntariado en la plataforma.',
    iconName: 'Sparkles',
    category: 'IMPACTO',
    unlocked: true,
    earnedAt: '2026-08-21T09:00:00Z',
  },
  {
    id: 'badge_eco_guardian',
    title: 'Eco-Guardián de Cuencas',
    description: 'Participó activamente en jornadas de siembra y protección de ecosistemas nativos (ODS 15).',
    iconName: 'Leaf',
    category: 'ESPECIALIDAD',
    unlocked: true,
    earnedAt: '2026-08-25T17:00:00Z',
  },
  {
    id: 'badge_stem_mentor',
    title: 'Mentor STEM Digital',
    description: 'Dictó mentorías educativas en programación y robótica para la niñez (ODS 4).',
    iconName: 'Code',
    category: 'ESPECIALIDAD',
    unlocked: true,
    earnedAt: '2026-08-30T16:00:00Z',
  },
  {
    id: 'badge_silver_hours',
    title: 'Compromiso de Plata (20+ Horas)',
    description: 'Ha superado las 20 horas verificadas y certificadas con rigor ISO 26000.',
    iconName: 'Award',
    category: 'HORAS',
    unlocked: true,
    earnedAt: '2026-09-02T12:00:00Z',
  },
  {
    id: 'badge_gold_hours',
    title: 'Líder Transformador (50+ Horas)',
    description: 'Voluntario referente con más de 50 horas de impacto social comprobado.',
    iconName: 'Crown',
    category: 'HORAS',
    unlocked: false,
  },
  {
    id: 'badge_habeas_data',
    title: 'Identidad & Habeas Data',
    description: 'Perfil validado con consentimiento estricto de tratamiento de datos (Ley 1581 / GDPR).',
    iconName: 'ShieldCheck',
    category: 'COMPLIANCE',
    unlocked: true,
    earnedAt: '2026-08-20T10:00:00Z',
  },
];

export const INITIAL_USERS: User[] = [
  {
    id: 'usr_super_1',
    name: 'Elena Rivas',
    email: 'elena.rivas@volunta.org',
    avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
    role: 'SUPER_ADMIN',
  },
  {
    id: 'usr_ong_1',
    name: 'Carlos Mendoza',
    email: 'carlos@bosquesandinos.org',
    avatarUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    role: 'ONG_ADMIN',
    organizationId: 'org_ong_1',
    organizationName: 'Fundación Bosques Andinos',
    phone: '+57 310 456 7890',
  },
  {
    id: 'usr_ong_2',
    name: 'Dra. Patricia Gómez',
    email: 'patricia@semillasdelcaribe.org',
    avatarUrl: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    role: 'ONG_ADMIN',
    organizationId: 'org_ong_2',
    organizationName: 'Corporación Semillas del Futuro',
    phone: '+57 312 890 1234',
  },
  {
    id: 'usr_empresa_1',
    name: 'Valeria Restrepo',
    email: 'vrestrepo@bancolombia-rse.com',
    avatarUrl: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    role: 'EMPRESA_RSE',
    organizationId: 'org_emp_1',
    organizationName: 'Grupo Bancolombia RSE',
    phone: '+57 315 222 3344',
  },
  {
    id: 'usr_empresa_2',
    name: 'Mauricio Salazar',
    email: 'msalazar@argos-sostenibilidad.co',
    avatarUrl: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    role: 'EMPRESA_RSE',
    organizationId: 'org_emp_2',
    organizationName: 'Cementos Argos Sostenibilidad',
    phone: '+57 318 777 8899',
  },
  {
    id: 'usr_vol_1',
    name: 'Andrés Morales',
    email: 'andres.morales@gmail.com',
    avatarUrl: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
    role: 'VOLUNTEER',
    skills: ['Reforestación', 'Biología', 'Fotografía de Campo'],
    totalVolunteeredHours: 24,
    phone: '+57 301 555 6789',
    badges: VOLUNTEER_BADGES.filter((b) => b.id !== 'badge_gold_hours'),
  },
  {
    id: 'usr_vol_2',
    name: 'Camila Herrera',
    email: 'camila.herrera@outlook.com',
    avatarUrl: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?w=150&auto=format&fit=crop&q=80',
    role: 'VOLUNTEER',
    skills: ['Programación Scratch', 'Pedagogía Infantil', 'Diseño Gráfico'],
    totalVolunteeredHours: 40,
    phone: '+57 320 987 6543',
    badges: VOLUNTEER_BADGES.filter((b) => b.id !== 'badge_eco_guardian'),
  },
];

export const INITIAL_ORGANIZATIONS: Organization[] = [
  {
    id: 'org_ong_1',
    name: 'Fundación Bosques Andinos',
    type: 'ONG',
    nit: '901.452.889-4',
    description: 'ONG dedicada a la restauración ecológica del bosque de niebla y protección de cuencas hídricas en la cordillera central.',
    website: 'https://bosquesandinos.org',
    contactEmail: 'contacto@bosquesandinos.org',
    contactPhone: '+57 (601) 745 2200',
    city: 'Manizales / Bogotá',
    country: 'Colombia',
    verificationStatus: 'ACTIVE',
    verifiedAt: '2026-08-10T14:30:00Z',
    verifiedBy: 'usr_super_1',
    complianceTags: ['ISO_14001_AMBIENTAL', 'ISO_26000_RSE'],
    createdAt: '2026-08-01T10:00:00Z',
  },
  {
    id: 'org_ong_2',
    name: 'Corporación Semillas del Futuro',
    type: 'ONG',
    nit: '900.812.334-1',
    description: 'Capacitación en robótica, pensamiento computacional y refuerzo escolar para niñas y niños en zonas rurales del Caribe.',
    website: 'https://semillasdelfuturo.org',
    contactEmail: 'info@semillasdelfuturo.org',
    contactPhone: '+57 (605) 388 9911',
    city: 'Santa Marta',
    country: 'Colombia',
    verificationStatus: 'ACTIVE',
    verifiedAt: '2026-08-14T09:15:00Z',
    verifiedBy: 'usr_super_1',
    complianceTags: ['ISO_26000_RSE', 'ISO_9001_CALIDAD'],
    createdAt: '2026-08-05T11:20:00Z',
  },
  {
    id: 'org_ong_3',
    name: 'Asociación Guardianes del Páramo',
    type: 'ONG',
    nit: '901.992.112-7',
    description: 'Monitoreo de frailejones y conservación del ecosistema de páramo con campesinos locales en Boyacá.',
    website: 'https://guardianesparamo.co',
    contactEmail: 'direccion@guardianesparamo.co',
    contactPhone: '+57 311 900 1122',
    city: 'Tunja',
    country: 'Colombia',
    verificationStatus: 'PENDING_VERIFICATION',
    complianceTags: ['ISO_14001_AMBIENTAL'],
    createdAt: '2026-09-15T16:00:00Z',
  },
  {
    id: 'org_emp_1',
    name: 'Grupo Bancolombia RSE',
    type: 'EMPRESA',
    nit: '890.903.938-8',
    description: 'Programa de Inversión Social y Voluntariado Corporativo enfocado en educación financiera y desarrollo rural regenerativo.',
    website: 'https://grupobancolombia.com/sostenibilidad',
    contactEmail: 'sostenibilidad@bancolombia.com.co',
    contactPhone: '+57 (604) 404 0000',
    city: 'Medellín',
    country: 'Colombia',
    verificationStatus: 'ACTIVE',
    verifiedAt: '2026-08-11T16:00:00Z',
    verifiedBy: 'usr_super_1',
    complianceTags: ['ISO_26000_RSE', 'ISO_27001_SEGURIDAD'],
    createdAt: '2026-08-02T12:00:00Z',
  },
  {
    id: 'org_emp_2',
    name: 'Cementos Argos Sostenibilidad',
    type: 'EMPRESA',
    nit: '890.900.161-3',
    description: 'Estrategia de valor compartido enfocada en infraestructura comunitaria sostenible y reforestación de hábitats degradados.',
    website: 'https://argos.co/sostenibilidad',
    contactEmail: 'rse@argos.co',
    contactPhone: '+57 (604) 319 8700',
    city: 'Barranquilla',
    country: 'Colombia',
    verificationStatus: 'ACTIVE',
    verifiedAt: '2026-08-12T11:00:00Z',
    verifiedBy: 'usr_super_1',
    complianceTags: ['ISO_14001_AMBIENTAL', 'ISO_26000_RSE'],
    createdAt: '2026-08-03T15:30:00Z',
  },
  {
    id: 'org_emp_3',
    name: 'Innovatech LatAm S.A.S',
    type: 'EMPRESA',
    nit: '901.764.550-9',
    description: 'Compañía de software B2B con programa de voluntariado pro-bono tecnológico y fondo de donación corporativa.',
    website: 'https://innovatechlatam.io',
    contactEmail: 'impacto@innovatechlatam.io',
    contactPhone: '+57 300 456 0000',
    city: 'Bogotá',
    country: 'Colombia',
    verificationStatus: 'PENDING_VERIFICATION',
    complianceTags: ['ISO_27001_SEGURIDAD'],
    createdAt: '2026-09-16T18:00:00Z',
  },
];

export const INITIAL_PROJECTS: Project[] = [
  {
    id: 'prj_1',
    organizationId: 'org_ong_1',
    organizationName: 'Fundación Bosques Andinos',
    title: 'Reforestación de 5.000 Árboles Nativos en Cuenca Alta del Río San Francisco',
    summary: 'Restauración de 10 hectáreas de microcuencas con especies nativas (Aliso, Cedro de Montaña) con participación de comunidades rurales.',
    description: 'Este proyecto interviene 10 hectáreas deforestadas mediante siembra directa, mantenimiento durante 12 meses y talleres de educación hídrica con los acueductos veredales. Buscamos tanto empresas aliadas que financien insumos agrícolas y cerramientos, como voluntarios para jornadas masivas de siembra y team building corporativo.',
    category: 'AMBIENTAL',
    status: 'PUBLISHED',
    city: 'Guasca, Cundinamarca',
    country: 'Colombia',
    isRemote: false,
    modality: 'PRESENCIAL',
    dedication: 'PUNTUAL',
    startDate: '2026-10-15',
    endDate: '2027-04-30',
    odsNumber: 15, // Vida de ecosistemas terrestres
    isoStandards: ['ISO_14001_AMBIENTAL', 'ISO_26000_RSE'],
    meetingPoint: 'Parque Principal de Guasca (Transporte en van coordinado por la ONG)',
    insuranceProvided: true,
    trainingProvided: true,
    corporateTeamCapacity: 30, // Cupos para Team Volunteering corporativo
    impactMetrics: {
      metricLabel: 'Árboles Nativos Plantados',
      currentValue: 1850,
      targetValue: 5000,
      unit: 'árboles',
      co2KgMitigated: 4200,
      sroiEstimatedRate: 95000, // COP por hora de voluntariado generada
    },
    fundingGoals: [
      {
        currency: 'COP',
        targetAmount: 38000000,
        committedAmount: 25000000,
        description: 'Compra de 5.000 plántulas nativas, abono orgánico y transporte de vivero comunitario.',
      },
    ],
    volunteerRoles: [
      {
        id: 'slot_1',
        title: 'Líder de Cuadrilla de Siembra',
        description: 'Coordinar grupos de 10 voluntarios en terreno para trazado de hoyado y fertilización inicial.',
        spotsTotal: 8,
        spotsFilled: 5,
        requiredSkills: ['Trabajo en equipo', 'Resistencia física media', 'Orientación ecológica'],
        estimatedHours: 16,
        modality: 'PRESENCIAL',
        dedication: 'PUNTUAL',
        competenciesDeveloped: ['Liderazgo de equipos', 'Gestión ambiental de campo', 'Resolución de problemas'],
        materialsIncluded: ['Póliza de accidentes de voluntariado', 'Herramientas y guantes de carnaza', 'Refrigerio campesino e hidratación'],
      },
      {
        id: 'slot_2',
        title: 'Fotógrafo & Documentalista de Biodiversidad',
        description: 'Registro audiovisual de la jornada y fichas fotográficas de las especies sembradas para memoria de sostenibilidad.',
        spotsTotal: 3,
        spotsFilled: 2,
        requiredSkills: ['Fotografía digital', 'Edición básica'],
        estimatedHours: 8,
        modality: 'PRESENCIAL',
        dedication: 'PUNTUAL',
        competenciesDeveloped: ['Comunicación visual para impacto', 'Narrativa de sostenibilidad'],
        materialsIncluded: ['Chaleco distintivo de Volunta', 'Certificado oficial de fotodocumentalismo'],
      },
    ],
    createdAt: '2026-08-15T10:00:00Z',
    approvedBy: 'usr_super_1',
    approvedAt: '2026-08-16T14:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1542601906990-b4d3fb778b09?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'prj_2',
    organizationId: 'org_ong_2',
    organizationName: 'Corporación Semillas del Futuro',
    title: 'Aulas Digitales & Pensamiento Computacional para 120 Niñas del Caribe',
    summary: 'Laboratorios móviles de programación con Raspberry Pi y robótica básica para cerrar la brecha de género STEM en colegios públicos.',
    description: 'El proyecto dotará a 4 escuelas rurales de la Sierra Nevada con kits offline de Scratch y microcontroladores. Requerimos patrocinio corporativo para los equipos físicos y mentores voluntarios que dicten talleres virtuales y presenciales durante 6 meses.',
    category: 'EDUCACION',
    status: 'PUBLISHED',
    city: 'Ciénaga, Magdalena',
    country: 'Colombia',
    isRemote: true,
    modality: 'VIRTUAL',
    dedication: 'RECURRENTE',
    startDate: '2026-11-01',
    endDate: '2027-05-30',
    odsNumber: 4, // Educación de Calidad
    isoStandards: ['ISO_26000_RSE', 'ISO_9001_CALIDAD'],
    insuranceProvided: false,
    trainingProvided: true,
    corporateTeamCapacity: 15,
    impactMetrics: {
      metricLabel: 'Niñas Capacitadas en Código',
      currentValue: 65,
      targetValue: 120,
      unit: 'estudiantes',
      co2KgMitigated: 0,
      sroiEstimatedRate: 25, // USD por hora pro-bono
    },
    fundingGoals: [
      {
        currency: 'USD',
        targetAmount: 8500,
        committedAmount: 5000,
        description: 'Adquisición de 30 kits de robótica educativa y tabletas de bajo consumo con batería solar.',
      },
    ],
    volunteerRoles: [
      {
        id: 'slot_3',
        title: 'Mentor Virtual en Programación Scratch',
        description: 'Acompañar a parejas de estudiantes en sesiones remotas quincenales de 1.5 horas los sábados.',
        spotsTotal: 15,
        spotsFilled: 9,
        requiredSkills: ['Conocimientos básicos en programación', 'Paciencia pedagógica', 'Empatía'],
        estimatedHours: 20,
        modality: 'VIRTUAL',
        dedication: 'RECURRENTE',
        competenciesDeveloped: ['Habilidades pedagógicas', 'Mentoría inclusiva', 'Comunicación asertiva'],
        materialsIncluded: ['Guía curricular Scratch paso a paso', 'Plataforma LMS provista'],
      },
    ],
    createdAt: '2026-08-18T12:00:00Z',
    approvedBy: 'usr_super_1',
    approvedAt: '2026-08-19T08:30:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1509062522246-3755977927d7?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'prj_3',
    organizationId: 'org_ong_1',
    organizationName: 'Fundación Bosques Andinos',
    title: 'Vivero Comunitario de Alta Montaña & Guardianes del Agua',
    summary: 'Construcción participativa de un vivero bioclimático para propagación de frailejones y polylepis.',
    description: 'Proyecto en revisión técnica por Volunta para validar viabilidad hidrológica y salvaguardas ambientales.',
    category: 'AMBIENTAL',
    status: 'IN_REVIEW',
    city: 'Aquitania, Boyacá',
    country: 'Colombia',
    isRemote: false,
    modality: 'PRESENCIAL',
    dedication: 'RECURRENTE',
    startDate: '2026-12-01',
    endDate: '2027-06-30',
    odsNumber: 6, // Agua Limpia y Saneamiento
    isoStandards: ['ISO_14001_AMBIENTAL'],
    insuranceProvided: true,
    trainingProvided: true,
    corporateTeamCapacity: 20,
    impactMetrics: {
      metricLabel: 'Plántulas de Páramo Producidas',
      currentValue: 0,
      targetValue: 10000,
      unit: 'frailejones',
      co2KgMitigated: 800,
      sroiEstimatedRate: 95000,
    },
    fundingGoals: [
      {
        currency: 'COP',
        targetAmount: 22000000,
        committedAmount: 0,
        description: 'Materiales de bio-construcción, polisombras y sistema de riego por microaspersión.',
      },
    ],
    volunteerRoles: [
      {
        id: 'slot_4',
        title: 'Técnico en Propagación Vegetal',
        description: 'Capacitación a campesinos en recolección de semillas y sustratos de montaña.',
        spotsTotal: 4,
        spotsFilled: 0,
        requiredSkills: ['Agronomía', 'Ingeniería Forestal o afines'],
        estimatedHours: 24,
        modality: 'PRESENCIAL',
        dedication: 'RECURRENTE',
        competenciesDeveloped: ['Transferencia tecnológica comunitaria', 'Manejo agroecológico'],
      },
    ],
    createdAt: '2026-09-14T11:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1464822759023-fed622ff2c3b?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'prj_4',
    organizationId: 'org_ong_2',
    organizationName: 'Corporación Semillas del Futuro',
    title: 'Consultoría Legal & Financiera Pro-Bono para Microempresarias Rurales',
    summary: 'Asesoría jurídica y contable personalizada para 45 cooperativas de mujeres artesanas y campesinas.',
    description: 'Programa de voluntariado profesional corporativo de alto valor. Profesionales en derecho mercantil, contabilidad y estrategia de negocios donan 3 horas mensuales para formalizar emprendimientos y abrir canales digitales.',
    category: 'PRO_BONO_PROFESIONAL',
    status: 'PUBLISHED',
    city: 'Santa Marta / Remoto',
    country: 'Colombia',
    isRemote: true,
    modality: 'HIBRIDO',
    dedication: 'RECURRENTE',
    startDate: '2026-10-01',
    endDate: '2027-03-31',
    odsNumber: 8, // Trabajo Decente y Crecimiento Económico
    isoStandards: ['ISO_26000_RSE', 'ISO_9001_CALIDAD'],
    insuranceProvided: false,
    trainingProvided: true,
    corporateTeamCapacity: 10,
    impactMetrics: {
      metricLabel: 'Microempresas Rurales Formalizadas',
      currentValue: 18,
      targetValue: 45,
      unit: 'emprendimientos',
      co2KgMitigated: 0,
      sroiEstimatedRate: 140000, // COP/hora de valor profesional pro-bono
    },
    fundingGoals: [
      {
        currency: 'COP',
        targetAmount: 18000000,
        committedAmount: 12000000,
        description: 'Costos de registro en Cámara de Comercio, RUT y software contable cloud para las beneficiarias.',
      },
    ],
    volunteerRoles: [
      {
        id: 'slot_5',
        title: 'Asesor Pro-Bono en Estructuración Financiera',
        description: 'Diagnosticar flujo de caja, fijación de precios justos y bancarización digital de artesanas.',
        spotsTotal: 6,
        spotsFilled: 4,
        requiredSkills: ['Finanzas', 'Contabilidad', 'Excel avanzado'],
        estimatedHours: 15,
        modality: 'HIBRIDO',
        dedication: 'RECURRENTE',
        competenciesDeveloped: ['Consultoría social', 'Adaptación de lenguaje técnico', 'Empatía económica'],
        materialsIncluded: ['Modelos de plantillas contables simplificadas', 'Diagnósticos previos de las asociaciones'],
      },
    ],
    createdAt: '2026-08-25T10:00:00Z',
    approvedBy: 'usr_super_1',
    approvedAt: '2026-08-26T15:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1573164713988-8665fc963095?w=800&auto=format&fit=crop&q=80',
  },
  {
    id: 'prj_5',
    organizationId: 'org_ong_1',
    organizationName: 'Fundación Bosques Andinos',
    title: 'Comedores Comunitarios & Rescate de Alimentos para 200 Familias',
    summary: 'Recuperación de frutas y verduras en plazas de mercado y preparación de viandas calientes con valor nutricional.',
    description: 'Jornadas de fin de semana para clasificar alimentos frescos rescatados del desperdicio y distribución a hogares vulnerables y personas mayores en el sur de Bogotá.',
    category: 'SOCIAL_COMUNITARIO',
    status: 'PUBLISHED',
    city: 'Bogotá (Usme y Ciudad Bolívar)',
    country: 'Colombia',
    isRemote: false,
    modality: 'PRESENCIAL',
    dedication: 'PUNTUAL',
    startDate: '2026-10-20',
    endDate: '2027-02-28',
    odsNumber: 2, // Hambre Cero
    isoStandards: ['ISO_26000_RSE'],
    meetingPoint: 'Centro Comunitario La Esperanza (Cra 14 # 85 Sur, Usme)',
    insuranceProvided: true,
    trainingProvided: true,
    corporateTeamCapacity: 25,
    impactMetrics: {
      metricLabel: 'Kilogramos de Alimentos Rescatados',
      currentValue: 3400,
      targetValue: 8000,
      unit: 'kg de comida',
      co2KgMitigated: 2100,
      sroiEstimatedRate: 85000,
    },
    fundingGoals: [
      {
        currency: 'COP',
        targetAmount: 14000000,
        committedAmount: 8500000,
        description: 'Empaque biodegradable, combustible para camionetas de acopio y dotación sanitaria.',
      },
    ],
    volunteerRoles: [
      {
        id: 'slot_6',
        title: 'Equipo de Acopio & Selección de Alimentos',
        description: 'Clasificación de productos agrícolas, pesaje y embalaje en canastillas sanitarias.',
        spotsTotal: 12,
        spotsFilled: 7,
        requiredSkills: ['Entusiasmo', 'Trabajo en equipo', 'Compromiso social'],
        estimatedHours: 6,
        modality: 'PRESENCIAL',
        dedication: 'PUNTUAL',
        competenciesDeveloped: ['Sensibilidad comunitaria', 'Logística inversa', 'Economía circular'],
        materialsIncluded: ['Póliza de seguro', 'Delantal y cofia reglamentaria', 'Almuerzo comunitario compartido'],
      },
    ],
    createdAt: '2026-08-28T09:00:00Z',
    approvedBy: 'usr_super_1',
    approvedAt: '2026-08-29T11:00:00Z',
    imageUrl: 'https://images.unsplash.com/photo-1488521787991-ed7bbaae773c?w=800&auto=format&fit=crop&q=80',
  },
];

export const INITIAL_CORPORATE_BOOKINGS: CorporateTeamBooking[] = [
  {
    id: 'corp_book_1',
    projectId: 'prj_1',
    projectTitle: 'Reforestación de 5.000 Árboles Nativos',
    ongOrganizationId: 'org_ong_1',
    empresaOrganizationId: 'org_emp_1',
    empresaName: 'Grupo Bancolombia RSE',
    teamSize: 15,
    preferredDate: '2026-11-14',
    contactPerson: 'Valeria Restrepo',
    contactEmail: 'vrestrepo@bancolombia-rse.com',
    contactPhone: '+57 315 222 3344',
    status: 'CONFIRMED',
    matchingGiftEnabled: true,
    matchingGiftPerHour: 40000,
    matchingGiftCurrency: 'COP',
    notes: 'Jornada de voluntariado de fin de año del equipo de Sostenibilidad e Inversión de Impacto.',
    createdAt: '2026-08-22T16:00:00Z',
  },
];

export const INITIAL_SPONSORSHIPS: SponsorshipIntent[] = [
  {
    id: 'spon_1',
    projectId: 'prj_1',
    projectTitle: 'Reforestación de 5.000 Árboles Nativos en Cuenca Alta del Río San Francisco',
    ongOrganizationId: 'org_ong_1',
    empresaOrganizationId: 'org_emp_1',
    empresaName: 'Grupo Bancolombia RSE',
    amount: 25000000,
    currency: 'COP',
    status: 'AGREED',
    contactPerson: 'Valeria Restrepo',
    contactEmail: 'vrestrepo@bancolombia-rse.com',
    contactPhone: '+57 315 222 3344',
    notes: 'Aporte alineado a nuestra meta de neutralidad de carbono 2030. Solicitamos informe trimestral con fotos georreferenciadas de siembra.',
    createdAt: '2026-08-20T15:30:00Z',
  },
  {
    id: 'spon_2',
    projectId: 'prj_2',
    projectTitle: 'Aulas Digitales & Pensamiento Computacional para 120 Niñas del Caribe',
    ongOrganizationId: 'org_ong_2',
    empresaOrganizationId: 'org_emp_2',
    empresaName: 'Cementos Argos Sostenibilidad',
    amount: 5000,
    currency: 'USD',
    status: 'AGREED',
    contactPerson: 'Mauricio Salazar',
    contactEmail: 'msalazar@argos-sostenibilidad.co',
    contactPhone: '+57 318 777 8899',
    notes: 'Patrocinio aprobado por el comité de RSE. Inclusión de 20 voluntarios corporativos en mentorías.',
    createdAt: '2026-08-25T11:15:00Z',
  },
];

export const INITIAL_APPLICATIONS: VolunteerApplication[] = [
  {
    id: 'app_1',
    projectId: 'prj_1',
    projectTitle: 'Reforestación de 5.000 Árboles Nativos',
    ongOrganizationId: 'org_ong_1',
    roleSlotId: 'slot_1',
    roleTitle: 'Líder de Cuadrilla de Siembra',
    volunteerUserId: 'usr_vol_1',
    volunteerName: 'Andrés Morales',
    volunteerEmail: 'andres.morales@gmail.com',
    volunteerPhone: '+57 301 555 6789',
    status: 'ACCEPTED',
    motivation: 'Soy biólogo con 3 años de experiencia en viveros de alta montaña. Quiero apoyar la conservación del agua en mi región.',
    hoursCommitted: 16,
    verifiedHours: 16,
    habeasDataAccepted: true,
    createdAt: '2026-08-21T09:00:00Z',
  },
  {
    id: 'app_2',
    projectId: 'prj_2',
    projectTitle: 'Aulas Digitales & Pensamiento Computacional',
    ongOrganizationId: 'org_ong_2',
    roleSlotId: 'slot_3',
    roleTitle: 'Mentor Virtual en Programación Scratch',
    volunteerUserId: 'usr_vol_2',
    volunteerName: 'Camila Herrera',
    volunteerEmail: 'camila.herrera@outlook.com',
    volunteerPhone: '+57 320 987 6543',
    status: 'ACCEPTED',
    motivation: 'Soy ingeniera de sistemas y quiero motivar a más niñas a descubrir la belleza de la tecnología y romper estereotipos.',
    hoursCommitted: 20,
    verifiedHours: 20,
    habeasDataAccepted: true,
    createdAt: '2026-08-26T14:30:00Z',
  },
];

export const INITIAL_AUDIT_LOGS: AuditLogEntry[] = [
  {
    traceId: 'trc_init_001',
    timestamp: '2026-08-10T14:30:00Z',
    userId: 'usr_super_1',
    userName: 'Elena Rivas',
    userRole: 'SUPER_ADMIN',
    action: 'ORGANIZATION_VERIFIED',
    resourceType: 'ORGANIZATION',
    resourceId: 'org_ong_1',
    severity: 'AUDIT',
    details: {
      organizationName: 'Fundación Bosques Andinos',
      nit: '901.452.889-4',
      isoCompliance: ['ISO_14001_AMBIENTAL', 'ISO_26000_RSE'],
    },
    ipAddress: '190.144.15.22 (Bogotá, CO)',
  },
  {
    traceId: 'trc_init_002',
    timestamp: '2026-08-16T14:00:00Z',
    userId: 'usr_super_1',
    userName: 'Elena Rivas',
    userRole: 'SUPER_ADMIN',
    action: 'PROJECT_APPROVED_PUBLISHED',
    resourceType: 'PROJECT',
    resourceId: 'prj_1',
    severity: 'AUDIT',
    details: {
      title: 'Reforestación de 5.000 Árboles Nativos',
      ods: 15,
      fundingGoal: '38,000,000 COP',
    },
    ipAddress: '190.144.15.22 (Bogotá, CO)',
  },
  {
    traceId: 'trc_init_003',
    timestamp: '2026-08-20T15:30:00Z',
    userId: 'usr_empresa_1',
    userName: 'Valeria Restrepo',
    userRole: 'EMPRESA_RSE',
    action: 'SPONSORSHIP_INTENT_REGISTERED',
    resourceType: 'SPONSORSHIP',
    resourceId: 'spon_1',
    severity: 'INFO',
    details: {
      projectId: 'prj_1',
      amount: 25000000,
      currency: 'COP',
      empresa: 'Grupo Bancolombia RSE',
    },
    ipAddress: '181.137.90.11 (Medellín, CO)',
  },
  {
    traceId: 'trc_init_004',
    timestamp: '2026-09-14T11:05:00Z',
    userId: 'usr_ong_1',
    userName: 'Carlos Mendoza',
    userRole: 'ONG_ADMIN',
    action: 'PROJECT_SUBMITTED_FOR_REVIEW',
    resourceType: 'PROJECT',
    resourceId: 'prj_3',
    severity: 'INFO',
    details: {
      title: 'Vivero Comunitario de Alta Montaña & Guardianes del Agua',
      organizationId: 'org_ong_1',
    },
    ipAddress: '190.25.10.88 (Manizales, CO)',
  },
];

export const INITIAL_PRO_BONO_DELIVERABLES: ProBonoDeliverable[] = [
  {
    id: 'pb_deliv_001',
    projectId: 'prj_1',
    projectTitle: 'Reforestación Cuenca Alta del Río Bogotá & Corredor Biológico',
    ongOrganizationId: 'org_ong_1',
    empresaOrganizationId: 'org_emp_1',
    volunteerUserId: 'usr_vol_1',
    volunteerName: 'Dra. Valentina Ríos',
    volunteerPseudonym: 'VOL-CO-9482',
    professionalCategory: 'LEGAL',
    title: 'Blindaje Jurídico de Servidumbres Ecológicas y Custodia de Tierras',
    description: 'Redacción y formalización de contratos de servidumbre ecológica y protocolos de custodia de predios ribereños con familias campesinas.',
    evidenceUrl: 'https://docs.nexusimpact.org/legal/evidencias/servidumbre-ecologica-rio-bogota.pdf',
    hoursWorked: 18,
    hourlyBenchmarkRate: 180000,
    currency: 'COP',
    country: 'CO',
    economicValuation: 3240000,
    status: 'ONG_APPROVED',
    beneficiariesImpacted: 85,
    submittedAt: '2026-08-28T14:30:00Z',
    approvedAt: '2026-08-29T16:00:00Z',
    approvedBy: 'Carlos Mendoza (Director Legal Fundación Bosques)',
    feedbackFromOng: 'Entregable impecable. Aprobado con los más altos estándares jurídicos de la Ley 1581 y Código Civil.',
    sha256VerificationHash: '8a9f4c3b2e1d0f8a7e6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f',
  },
  {
    id: 'pb_deliv_002',
    projectId: 'prj_2',
    projectTitle: 'Semilleros de Programación y Robótica Rural para la Niñez',
    ongOrganizationId: 'org_ong_2',
    empresaOrganizationId: 'org_emp_1',
    volunteerUserId: 'usr_vol_1',
    volunteerName: 'Valentina Ríos',
    volunteerPseudonym: 'VOL-CO-9482',
    professionalCategory: 'TECH',
    title: 'Arquitectura Cloud Segura y Plataforma LMS de Código Abierto',
    description: 'Despliegue de plataforma Moodle cloud para 250 niñas y niños rurales con optimización para baja conectividad y cifrado de datos.',
    evidenceUrl: 'https://github.com/fundacion-semilleros/lms-rural-deployment',
    hoursWorked: 26,
    hourlyBenchmarkRate: 150000,
    currency: 'COP',
    country: 'CO',
    economicValuation: 3900000,
    status: 'ONG_APPROVED',
    beneficiariesImpacted: 250,
    submittedAt: '2026-09-02T10:15:00Z',
    approvedAt: '2026-09-03T11:45:00Z',
    approvedBy: 'Dra. María Elena Restrepo (Directora Ejecutiva)',
    feedbackFromOng: 'Permite impartir clases a 12 veredas sin interrumpir el servicio.',
    sha256VerificationHash: '3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e',
  },
  {
    id: 'pb_deliv_003',
    projectId: 'prj_1',
    projectTitle: 'Reforestación Cuenca Alta del Río Bogotá & Corredor Biológico',
    ongOrganizationId: 'org_ong_1',
    empresaOrganizationId: 'org_emp_1',
    volunteerUserId: 'usr_vol_2',
    volunteerName: 'Ing. Mateo Gómez',
    volunteerPseudonym: 'VOL-CO-4120',
    professionalCategory: 'ESG_CONSULTING',
    title: 'Estimación de Captura de Carbono (ISO 14064 / GRI 305)',
    description: 'Protocolo de medición biométrica de biomasa y balance de GEI para certificación de 1,200 árboles nativos sembrados.',
    evidenceUrl: 'https://docs.nexusimpact.org/esg/reportes/balance-gei-cuenca-bogota-2026.pdf',
    hoursWorked: 20,
    hourlyBenchmarkRate: 170000,
    currency: 'COP',
    country: 'CO',
    economicValuation: 3400000,
    status: 'ONG_APPROVED',
    beneficiariesImpacted: 140,
    submittedAt: '2026-09-05T09:00:00Z',
    approvedAt: '2026-09-06T15:20:00Z',
    approvedBy: 'Carlos Mendoza',
    feedbackFromOng: 'Cálculos validados con tablas del IDEAM.',
    sha256VerificationHash: '5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b',
  },
  {
    id: 'pb_deliv_004',
    projectId: 'prj_3',
    projectTitle: 'Vivero Comunitario de Alta Montaña & Guardianes del Agua',
    ongOrganizationId: 'org_ong_1',
    empresaOrganizationId: 'org_emp_1',
    volunteerUserId: 'usr_vol_3',
    volunteerName: 'Camila Morales',
    volunteerPseudonym: 'VOL-CO-7719',
    professionalCategory: 'FINANCE',
    title: 'Estructuración de Flujo de Caja y Presupuesto Maestro para Vivero',
    description: 'Plan financiero plurianual con modelos de sostenibilidad de autosuficiencia y venta de plántulas nativas a juntas de acción comunal.',
    evidenceUrl: 'https://docs.nexusimpact.org/finance/modelos/vivero-comunitario-flujo-caja.xlsx',
    hoursWorked: 15,
    hourlyBenchmarkRate: 160000,
    currency: 'COP',
    country: 'CO',
    economicValuation: 2400000,
    status: 'ONG_APPROVED',
    beneficiariesImpacted: 60,
    submittedAt: '2026-09-10T17:00:00Z',
    approvedAt: '2026-09-11T12:00:00Z',
    approvedBy: 'Carlos Mendoza',
    feedbackFromOng: 'Excelente herramienta para sustentar solicitudes de cofinanciamiento.',
    sha256VerificationHash: '9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c',
  },
  {
    id: 'pb_deliv_005',
    projectId: 'prj_4',
    projectTitle: 'Huertos Urbanos Sostenibles & Seguridad Alimentaria',
    ongOrganizationId: 'org_ong_2',
    empresaOrganizationId: 'org_emp_1',
    volunteerUserId: 'usr_vol_1',
    volunteerName: 'Valentina Ríos',
    volunteerPseudonym: 'VOL-CO-9482',
    professionalCategory: 'LEGAL',
    title: 'Reglamento de Uso y Custodia de Huertos Comunitarios',
    description: 'Protocolo de convivencia y cesión de espacios comunales aprobado por la asamblea vecinal.',
    evidenceUrl: 'https://docs.nexusimpact.org/legal/reglamentos/huerto-urbano-convivencia.pdf',
    hoursWorked: 12,
    hourlyBenchmarkRate: 180000,
    currency: 'COP',
    country: 'CO',
    economicValuation: 2160000,
    status: 'SUBMITTED',
    beneficiariesImpacted: 45,
    submittedAt: '2026-09-17T11:00:00Z',
    sha256VerificationHash: '7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a',
  },
];

export const INITIAL_ARCO_REQUESTS: ArcoRequest[] = [
  {
    id: 'arco_001',
    userId: 'usr_vol_1',
    userName: 'Valentina Ríos',
    userEmail: 'valentina.rios@example.com',
    country: 'CO',
    rightType: 'ACCESS_KNOW',
    status: 'COMPLETED',
    details: 'Solicitud de copia íntegra de constancias de horas Pro-Bono y registros de consentimiento bajo Ley 1581 de 2012.',
    resolutionNotes: 'Certificado de trazabilidad y reporte de datos personales expedido y enviado a la titular.',
    requestedAt: '2026-08-25T10:00:00Z',
    resolvedAt: '2026-08-26T15:30:00Z',
    legalDeadline: '2026-09-15T23:59:59Z',
  },
  {
    id: 'arco_002',
    userId: 'usr_vol_2',
    userName: 'Mateo Gómez',
    userEmail: 'mateo.gomez@example.com',
    country: 'CO',
    rightType: 'RECTIFICATION',
    status: 'COMPLETED',
    details: 'Actualización de registro de correo corporativo y tarjeta profesional de ingeniería.',
    resolutionNotes: 'Datos rectificados y validados en el directorio de talento Pro-Bono.',
    requestedAt: '2026-09-01T08:20:00Z',
    resolvedAt: '2026-09-01T14:10:00Z',
    legalDeadline: '2026-09-22T23:59:59Z',
  },
  {
    id: 'arco_003',
    userId: 'usr_vol_3',
    userName: 'Camila Morales',
    userEmail: 'camila.morales@example.com',
    country: 'CL',
    rightType: 'OPPOSITION_PORTABILITY',
    status: 'IN_REVIEW',
    details: 'Solicitud de portabilidad de horas de voluntariado certificadas en formato interoperable JSON Schema según estándar CMF.',
    requestedAt: '2026-09-16T12:00:00Z',
    legalDeadline: '2026-09-18T23:59:59Z',
  },
];

export const INITIAL_AUDIT_BLOCKS: CryptographicAuditBlock[] = [
  {
    blockIndex: 0,
    timestamp: '2026-08-01T00:00:00Z',
    country: 'CO',
    eventType: 'VOLUNTEER_CHECKIN',
    actorPseudonym: 'GENESIS-SYSTEM',
    projectId: 'SYSTEM-ROOT',
    payloadHash: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    previousBlockHash: '0000000000000000000000000000000000000000000000000000000000000000',
    currentBlockHash: '00000a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789ab',
    rfc3161TimestampToken: 'TSA-GENESIS-20260801-0001',
  },
  {
    blockIndex: 1,
    timestamp: '2026-08-29T16:00:00Z',
    country: 'CO',
    eventType: 'HOURS_VALIDATED_ONG',
    actorPseudonym: 'VOL-CO-9482',
    projectId: 'prj_1',
    payloadHash: '8a9f4c3b2e1d0f8a7e6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f',
    previousBlockHash: '00000a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789ab',
    currentBlockHash: '7b2a8f9c1e0d3b5a7c9e1f3d5b7a9c1e3f5d7b9a1c3e5f7b9a1c3e5f7b9a1c3e',
    rfc3161TimestampToken: 'TSA-CERTICAMARA-20260829-9482',
  },
  {
    blockIndex: 2,
    timestamp: '2026-09-03T11:45:00Z',
    country: 'CO',
    eventType: 'HOURS_VALIDATED_ONG',
    actorPseudonym: 'VOL-CO-9482',
    projectId: 'prj_2',
    payloadHash: '3f2e1d0c9b8a7f6e5d4c3b2a1f0e9d8c7b6a5f4e3d2c1b0a9f8e7d6c5b4a3f2e',
    previousBlockHash: '7b2a8f9c1e0d3b5a7c9e1f3d5b7a9c1e3f5d7b9a1c3e5f7b9a1c3e5f7b9a1c3e',
    currentBlockHash: '4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c',
    rfc3161TimestampToken: 'TSA-CERTICAMARA-20260903-8821',
  },
  {
    blockIndex: 3,
    timestamp: '2026-09-06T15:20:00Z',
    country: 'CO',
    eventType: 'HOURS_VALIDATED_ONG',
    actorPseudonym: 'VOL-CO-4120',
    projectId: 'prj_1',
    payloadHash: '5c4b3a2f1e0d9c8b7a6f5e4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b',
    previousBlockHash: '4d3c2b1a0f9e8d7c6b5a4f3e2d1c0b9a8f7e6d5c4b3a2f1e0d9c8b7a6f5e4d3c',
    currentBlockHash: '1a2b3c4d5e6f7a8b9c0d1e2f3a4b5c6d7e8f9a0b1c2d3e4f5a6b7c8d9e0f1a2b',
    rfc3161TimestampToken: 'TSA-CERTICAMARA-20260906-4120',
  },
];

// INITIAL TOKEN WALLETS (Impact Tokens / VIT)
export const INITIAL_TOKEN_WALLETS: ImpactTokenWallet[] = [
  {
    id: 'wlt_vol_1',
    userId: 'usr_vol_1',
    userName: 'Andrés Morales',
    volunteerPseudonym: 'VOL-CO-9482',
    balance: 380, // 380 VIT
    totalMinted: 480,
    totalRedeemed: 100,
    level: 'PLATA',
    adhesionTermSigned: true,
    adhesionTermSignedAt: '2026-08-20T10:00:00Z',
    adhesionLegalFramework: 'LEY_720_COLOMBIA',
    updatedAt: '2026-09-18T14:30:00Z',
  },
  {
    id: 'wlt_vol_2',
    userId: 'usr_vol_2',
    userName: 'Camila Herrera',
    volunteerPseudonym: 'VOL-CO-4120',
    balance: 620, // 620 VIT
    totalMinted: 720,
    totalRedeemed: 100,
    level: 'ORO',
    adhesionTermSigned: true,
    adhesionTermSignedAt: '2026-08-18T12:00:00Z',
    adhesionLegalFramework: 'LEY_720_COLOMBIA',
    updatedAt: '2026-09-19T09:15:00Z',
  },
];

// INITIAL TOKEN TRANSACTIONS
export const INITIAL_TOKEN_TRANSACTIONS: ImpactTokenTransaction[] = [
  {
    id: 'tx_vit_001',
    walletId: 'wlt_vol_1',
    userId: 'usr_vol_1',
    userName: 'Andrés Morales',
    type: 'MINT_HOURS',
    amount: 120,
    projectId: 'prj_1',
    projectTitle: 'Reforestación Bosque Altoandino Guavio',
    ongOrganizationId: 'org_ong_1',
    ongName: 'Fundación Bosques Andinos',
    reason: '12 Horas de Siembra Presencial Verificadas en Terreno (10 VIT/h)',
    legalNonRemunerationNotice: 'Incentivo honorífico no dinerario conforme a Ley 720 de 2001 (Art. 6). No constituye salario ni relación laboral.',
    sha256ProofHash: 'a1b2c3d4e5f67890123456789abcdef0123456789abcdef0123456789abcdef0',
    timestamp: '2026-08-29T16:05:00Z',
  },
  {
    id: 'tx_vit_002',
    walletId: 'wlt_vol_1',
    userId: 'usr_vol_1',
    userName: 'Andrés Morales',
    type: 'MINT_PROBONO',
    amount: 250,
    projectId: 'prj_1',
    projectTitle: 'Reforestación Bosque Altoandino Guavio',
    ongOrganizationId: 'org_ong_1',
    ongName: 'Fundación Bosques Andinos',
    reason: 'Entregable Técnico GIS & Mapeo Satelital Aprobado (25 VIT/h)',
    legalNonRemunerationNotice: 'Reconocimiento a servicios pro-bono especializados exento de renta (Art. 125-2 ET / Dcto 4290).',
    sha256ProofHash: 'f0e1d2c3b4a5968778695a4b3c2d1e0f0123456789abcdefa1b2c3d4e5f67890',
    timestamp: '2026-09-02T18:30:00Z',
  },
  {
    id: 'tx_vit_003',
    walletId: 'wlt_vol_1',
    userId: 'usr_vol_1',
    userName: 'Andrés Morales',
    type: 'REDEEM_PERK',
    amount: -100,
    reason: 'Canje de Beca de Formación: Masterclass Certificada en Medición de Huella GHG (ISO 14064)',
    legalNonRemunerationNotice: 'Prestación de beneficio formativo en especie. No sujeto a retención en la fuente laboral.',
    sha256ProofHash: '3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4d3e2f1a0b9c8d7e6f5a4b3c2d',
    timestamp: '2026-09-10T11:20:00Z',
  },
  {
    id: 'tx_vit_004',
    walletId: 'wlt_vol_2',
    userId: 'usr_vol_2',
    userName: 'Camila Herrera',
    type: 'MINT_PROBONO',
    amount: 375,
    projectId: 'prj_2',
    projectTitle: 'Aulas Digitales Comunitarias',
    ongOrganizationId: 'org_ong_2',
    ongName: 'Corporación Semillas del Futuro',
    reason: 'Desarrollo de Currículo STEM y Acompañamiento a 45 Niños (15h x 25 VIT/h)',
    legalNonRemunerationNotice: 'Incentivo de reconocimiento benévolo en el marco de la Ley 720/2001.',
    sha256ProofHash: 'b5c4d3e2f1a0b9c8d7e6f5a4b3c2d1e0f9a8b7c6d5e4f3a2b1c0d9e8f7a6b5c4',
    timestamp: '2026-09-05T14:45:00Z',
  },
];

// SOULBOUND IMPACT BADGES (ERC-5192 Non-Transferable Proof of Impact)
export const INITIAL_SOULBOUND_BADGES: SoulboundImpactBadge[] = [
  {
    id: 'sbt_001',
    tokenId: 'SBT-ODS13-CLIMA-2026-0012',
    volunteerUserId: 'usr_vol_1',
    volunteerPseudonym: 'VOL-CO-9482',
    title: 'Custodio Climático Altoandino',
    odsNumber: 13,
    category: 'CLIMA',
    issuedByOngName: 'Fundación Bosques Andinos',
    verifiedHours: 24,
    economicValuationInKind: 3600000,
    currency: 'COP',
    erc5192NonTransferable: true,
    sha256CertificateHash: '8f4c2b1e0d9a7c5e3b1f0d8a6c4e2b0a9f7d5c3b1a0e8f6d4b2c0a9e7f5d3b1a',
    issuedAt: '2026-09-03T12:00:00Z',
  },
  {
    id: 'sbt_002',
    tokenId: 'SBT-ODS04-STEM-2026-0088',
    volunteerUserId: 'usr_vol_2',
    volunteerPseudonym: 'VOL-CO-4120',
    title: 'Arquitecto de Futuro STEM',
    odsNumber: 4,
    category: 'EDUCACION',
    issuedByOngName: 'Corporación Semillas del Futuro',
    verifiedHours: 40,
    economicValuationInKind: 6000000,
    currency: 'COP',
    erc5192NonTransferable: true,
    sha256CertificateHash: '4e2b0a9f7d5c3b1a0e8f6d4b2c0a9e7f5d3b1a8f4c2b1e0d9a7c5e3b1f0d8a6c',
    issuedAt: '2026-09-06T15:30:00Z',
  },
];

// IMPACT PERK REWARDS (Tax-neutral non-cash rewards sponsored by Empresas RSE)
export const INITIAL_PERK_REWARDS: ImpactPerkReward[] = [
  {
    id: 'perk_001',
    title: 'Beca Masterclass: Medición Huella de Carbono ISO 14064',
    category: 'EDUCACION',
    tokenCost: 100,
    sponsorCompanyName: 'Cementos Argos Sostenibilidad',
    sponsorOrgId: 'org_emp_2',
    description: 'Acceso completo con certificación internacional en cálculo de alcances 1, 2 y 3 bajo protocolo GHG.',
    taxExemptionStatus: 'Beneficio formativo no salarial exento conforme a Art. 125-2 ET.',
    availableStock: 25,
    iconName: 'GraduationCap',
    redemptionInstructions: 'Recibirás un cupón de acceso institucional y credencial académica a tu correo verificado.',
  },
  {
    id: 'perk_002',
    title: 'Siembra de 3 Árboles Nativos a tu Nombre en la Reserva',
    category: 'SOSTENIBILIDAD',
    tokenCost: 80,
    sponsorCompanyName: 'Grupo Bancolombia RSE',
    sponsorOrgId: 'org_emp_1',
    description: 'Protección de fuentes hídricas con monitoreo satelital anual y georreferenciación NFT de impacto.',
    taxExemptionStatus: 'Aporte de mitigación ambiental auditado ISO 14001 sin valor salarial para el voluntario.',
    availableStock: 80,
    iconName: 'Trees',
    redemptionInstructions: 'Se emitirá un certificado digital de custodia forestal firmado por la ONG aliada.',
  },
  {
    id: 'perk_003',
    title: 'Matching Donation de $250.000 COP a la ONG de tu Elección',
    category: 'DONACION_MATCH',
    tokenCost: 200,
    sponsorCompanyName: 'Grupo Bancolombia RSE',
    sponsorOrgId: 'org_emp_1',
    description: 'Bancolombia transfiere directamente 250.000 COP adicionales al proyecto social que selecciones.',
    taxExemptionStatus: 'Donación corporativa directa ONG con certificado tributario Art. 125-2 ET para la empresa.',
    availableStock: 15,
    iconName: 'HeartHandshake',
    redemptionInstructions: 'Elige la ONG activa y se liberará el aporte corporativo en el siguiente cierre contable.',
  },
  {
    id: 'perk_004',
    title: 'Kit de Economía Circular: Termo Solar + Mochila Reciclada PET',
    category: 'SOSTENIBILIDAD',
    tokenCost: 150,
    sponsorCompanyName: 'Cementos Argos Sostenibilidad',
    sponsorOrgId: 'org_emp_2',
    description: 'Kit de bajo impacto fabricado 100% con plásticos rescatados del río Magdalena por recicladores de oficio.',
    taxExemptionStatus: 'Obsequio conmemorativo benévolo en especie de promoción de economía circular.',
    availableStock: 30,
    iconName: 'Package',
    redemptionInstructions: 'Envío sin costo a tu dirección de residencia en Colombia, Chile o Brasil.',
  },
  {
    id: 'perk_005',
    title: 'Pase VIP a la Cumbre Latinoamericana de Sostenibilidad 2026',
    category: 'EXPERIENCIAS',
    tokenCost: 350,
    sponsorCompanyName: 'Grupo Bancolombia RSE',
    sponsorOrgId: 'org_emp_1',
    description: 'Entrada virtual con networking 1:1 con líderes ESG, directores de sostenibilidad y ONGs globales.',
    taxExemptionStatus: 'Beca de relacionamiento e intercambio formativo no dinerario.',
    availableStock: 10,
    iconName: 'Ticket',
    redemptionInstructions: 'Acceso directo a la plataforma del congreso con credencial de Voluntario de Honor.',
  },
];

// LEGAL ADHESION TERMS (Ley 720 Colombia / Ley 20.500 Chile / Lei 9.608 Brasil)
export const INITIAL_ADHESION_TERMS: LegalAdhesionTerm[] = [
  {
    id: 'adh_vol_1',
    userId: 'usr_vol_1',
    country: 'CO',
    lawReference: 'Ley 720 de 2001 y Decreto 4290 de 2005 (Colombia)',
    signedAt: '2026-08-20T10:00:00Z',
    noLaborRelationshipClause: true,
    sha256ConsentHash: 'c7a4d5e8f1b2c3d4e5f67890123456789abcdef0123456789abcdef012345678',
  },
  {
    id: 'adh_vol_2',
    userId: 'usr_vol_2',
    country: 'CO',
    lawReference: 'Ley 720 de 2001 y Decreto 4290 de 2005 (Colombia)',
    signedAt: '2026-08-18T12:00:00Z',
    noLaborRelationshipClause: true,
    sha256ConsentHash: 'd8b5e6f9a2c3d4e5f67890123456789abcdef0123456789abcdef0123456789a',
  },
];

